In the AI pipeline, Pandas is your data cleaning powerhouse. Before any data gets converted into tensors for neural networks, it spends most of its time sitting in a Pandas DataFrame being filtered, cleaned, and transformed.

1. Core Architecture: Series & DataFrames

Series (1D): A single labeled column (built on top of a 1D NumPy array).

DataFrame (2D): A table with labeled axes (rows and columns), where each column is a Series.

In [1]:
import pandas as pd 
#creating dataframes from a dictionary
data={
    "age":[22,25,28,None],
    "Score":[88,92,None,75],
    "Passed":[True,True,False,False]
}
df=pd.DataFrame(data)
print(df)

    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0    NaN   False
3   NaN   75.0   False

2. Essential ML Data Preprocessing Patterns

When preparing data for AI models, these are the top 4 operations you'll run constantly:

A. Handling Missing Data (Imputation)

Real-world datasets are messy. Neural networks will throw errors if they see NaN (Not a Number) values.

In [5]:
#Check Missing Values
print(df.isnull().sum())

#Fill missing numerical values with the mean/median
df["age"]=df["age"].fillna(df["age"].median())
df["Score"]=df["Score"].fillna(df["Score"].median())

print(df)

age       0
Score     1
Passed    0
dtype: int64
    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0   88.0   False
3  25.0   75.0   False

B. Filtering & Querying (Boolean Masking)

Just like NumPy boolean indexing, Pandas lets you filter rows using logical conditions.

In [7]:
# Filter rows where Score > 80
high_scorers = df[df["Score"] > 80]
print(high_scorers)

    age  Score  Passed
0  22.0   88.0    True
1  25.0   92.0    True
2  28.0   88.0   False

C. Feature Engineering & Mapping

Transforming text categories into numerical data so models can process them.

In [8]:
# Map boolean or categorical strings to 0/1
df["Passed"] = df["Passed"].astype(int)

D. Converting DataFrames back to NumPy Arrays

Once your data is cleaned, you convert it back to NumPy arrays (or PyTorch/TensorFlow tensors) for training.

In [12]:
# Extract features as a raw 2D NumPy array
X = df[["age", "Score" , "Passed"]].values
print(X)  # <class 'numpy.ndarray'>

[[22. 88.  1.]
 [25. 92.  1.]
 [28. 88.  0.]
 [25. 75.  0.]]

Pandas Series (1D)

A series is essentially a 1D Numpy array with an Index (row label)
Unlike NumPy arrays where you access elements only by position (scores[0]), in a Series you can access them by label (scores['Alice']) OR by position (scores.iloc[0]).

In [1]:
import pandas as pd
import numpy as np

# Creating a Series from a list
scores = pd.Series([85, 90, 78, 92], index=['Alice', 'Bob', 'Charlie', 'David'])
print(scores)

Alice      85
Bob        90
Charlie    78
David      92
dtype: int64

Pandas Dataframes (2D)

A DataFrame is a 2-dimensional table—think of an Excel sheet or a SQL table. Each column in a DataFrame is actually a Pandas Series.

In [2]:
# Creating a DataFrame from a dictionary of lists
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 92],
    "Passed": [True, True, False, True]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Score  Passed
0    Alice   24     85    True
1      Bob   27     90    True
2  Charlie   22     78   False
3    David   32     92    True

In [3]:
ai_df = pd.DataFrame({
    "Model_name" : ["Gemini","ChatGPT","Claude","Anthropic"],
    "Parameters_Billions":[70,100,200,300],
    "Accuracy":[90,80,75,95],
    "Is_opensource":[True,True,False,True]
})
print(ai_df)
print(ai_df.info())
acc_series=ai_df["Accuracy"]
print(type(acc_series))

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
1    ChatGPT                  100        80           True
2     Claude                  200        75          False
3  Anthropic                  300        95           True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Model_name           4 non-null      object
 1   Parameters_Billions  4 non-null      int64
 2   Accuracy             4 non-null      int64
 3   Is_opensource        4 non-null      bool
dtypes: bool(1), int64(2), object(1)
memory usage: 232.0+ bytes
None
<class 'pandas.core.series.Series'>

Data Selection & Indexing (loc vs iloc)

1. iloc (integer-location based)

Selects data using numerical index positions (0, 1, 2...), exactly like NumPy arrays.

In [5]:
# Format: df.iloc[row_index, column_index]

# Get the first row (Gemini)
print(ai_df.iloc[0])

# Get the first 2 rows, and first 2 columns
print(ai_df.iloc[0:2, 0:2])

Model_name             Gemini
Parameters_Billions        70
Accuracy                   90
Is_opensource            True
Name: 0, dtype: object
  Model_name  Parameters_Billions
0     Gemini                   70
1    ChatGPT                  100

2. loc (Label-location based)

Selects data using row labels and column names.

In [6]:
# Format: df.loc[row_label, column_name]

# Get all rows, but only 'Model_name' and 'Accuracy' columns
print(ai_df.loc[:, ["Model_name", "Accuracy"]])

  Model_name  Accuracy
0     Gemini        90
1    ChatGPT        80
2     Claude        75
3  Anthropic        95

3.Filtering Data (Boolean Indexing)

This is where Pandas shines for AI dataset preparation. You can filter rows based on conditions.

In [8]:
# Filter models where Accuracy is >= 80
high_acc = ai_df[ai_df["Accuracy"] >= 80]
print(high_acc)
print()
# Combine conditions with & (AND) or | (OR)
# Filter models that are Open Source AND have > 80 Accuracy
top_open_source = ai_df[(ai_df["Is_opensource"] == True) & (ai_df["Accuracy"] > 80)]
print(top_open_source)

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
1    ChatGPT                  100        80           True
3  Anthropic                  300        95           True

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
3  Anthropic                  300        95           True

In [15]:
print(ai_df.loc[[1,2],["Model_name","Parameters_Billions"]])
print()
print(ai_df.loc[ai_df["Parameters_Billions"]>90])

  Model_name  Parameters_Billions
1    ChatGPT                  100
2     Claude                  200

  Model_name  Parameters_Billions  Accuracy  Is_opensource
1    ChatGPT                  100        80           True
2     Claude                  200        75          False
3  Anthropic                  300        95           True

Importing and exporting data in Pandas

we will check for few most commonly used file formats

1. Comma Seperated Values (CSV)

CSVs are the most common data format in Machine Learning

In [ ]:
import pandas as pd

ai_df.to_csv('dataset.csv',index=False )
# 📥 IMPORT (Reading a CSV)
df = pd.read_csv('dataset.csv')
print(df)
df = pd.read_csv('dataset.csv',usecols=["Model_name","Accuracy"]) #Loads only the specified columns
print(df)
# 📤 EXPORT (Saving to a CSV)
# Always use index=False, otherwise Pandas will save row numbers (0, 1, 2...) as a column!
df.to_csv('cleaned_dataset.csv', index=False)
print(df)

  Model_name  Parameters_Billions  Accuracy  Is_opensource
0     Gemini                   70        90           True
1    ChatGPT                  100        80           True
2     Claude                  200        75          False
3  Anthropic                  300        95           True
  Model_name  Accuracy
0     Gemini        90
1    ChatGPT        80
2     Claude        75
3  Anthropic        95
  Model_name  Accuracy
0     Gemini        90
1    ChatGPT        80
2     Claude        75
3  Anthropic        95

2. Excel Files (.xlsx)

Pandas works seamlessly with Excel spreadsheets (requires the openpyxl library under the hood).

3. JSON Files (.json)

JSON is standard when fetching data from Web APIs or working with unstructured text data in Generative AI pipelines.

4. Converting directly to/from NumPy & Python Dicts

When moving data into deep learning frameworks (PyTorch or TensorFlow), you'll often convert DataFrames into NumPy arrays or Python dictionaries.

In [12]:
# DataFrame -> NumPy Array (for model input)
X_array = ai_df[['Parameters_Billions', 'Accuracy']].values
print(type(X_array)) 
# DataFrame -> Python Dictionary
data_dict = ai_df.to_dict(orient='records')
print(type(data_dict))
# Python Dictionary -> DataFrame
df_new = pd.DataFrame(data_dict)
print(type(df_new))

<class 'numpy.ndarray'>
<class 'list'>
<class 'pandas.core.frame.DataFrame'>

Lets do some Data Exploration,
for this instead of using our own small dataset, we will import data from scikit-learn library and we will explore its data set

In [37]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
df=fetch_california_housing(as_frame=True).frame
print(df)

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
...       ...       ...       ...        ...         ...       ...       ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

       Longitude  MedHouseVal
0        -122.23        4.526
1        -122.22        3.585
2        -122.24        3.521
3        -122.25        3.413
4        -122.25        3.422
...          ...          ...
20635    -121.09        0.781
20636    -121.21        0.771
20637    -121.22        0.923
20638    -121.32        0.847
20639    -121.24        0.894

[20640 rows x 9 columns]

In [15]:
print(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85

   Longitude  MedHouseVal
0    -122.23        4.526
1    -122.22        3.585
2    -122.24        3.521
3    -122.25        3.413
4    -122.25        3.422

In [16]:
print(df.head(10))

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
5  4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85
6  3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84
7  3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84
8  2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84
9  3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84

   Longitude  MedHouseVal
0    -122.23        4.526
1    -122.22        3.585
2    -122.24        3.521
3    -122.25        3.413
4    -122.25        3.422
5    -122.25        2.697
6    -122.25        2.992
7    -122.25        2.414
8    -122.26        2.267
9    -122.25        2.611

In [17]:
df.tail(10)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
20630,3.5673,11.0,5.932584,1.134831,1257.0,2.824719,39.29,-121.32,1.120
20631,3.5179,15.0,6.145833,1.141204,1200.0,2.777778,39.33,-121.40,1.072
20632,3.1250,15.0,6.023377,1.080519,1047.0,2.719481,39.26,-121.45,1.156
20633,2.5495,27.0,5.445026,1.078534,1082.0,2.832461,39.19,-121.53,0.983
20634,3.7125,28.0,6.779070,1.148256,1041.0,3.026163,39.27,-121.56,1.168
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [26]:
df.sample(5)  # Randomly sample 5 rows

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
7667,3.5250,39.0,4.618750,1.012500,1127.0,3.521875,33.93,-118.08,1.580
9533,3.6182,27.0,6.557143,1.211429,1252.0,3.577143,37.44,-120.75,1.232
7575,3.4485,38.0,5.076503,0.907104,686.0,3.748634,33.88,-118.21,1.194
12442,2.4250,16.0,5.080000,1.186667,182.0,2.426667,33.86,-116.08,0.761
2790,1.9722,34.0,4.286957,1.076522,1172.0,2.038261,37.36,-118.40,1.161

In [40]:
pd.options.display.max_columns=3
print(df)

       MedInc  ...  MedHouseVal
0      8.3252  ...        4.526
1      8.3014  ...        3.585
2      7.2574  ...        3.521
3      5.6431  ...        3.413
4      3.8462  ...        3.422
...       ...  ...          ...
20635  1.5603  ...        0.781
20636  2.5568  ...        0.771
20637  1.7000  ...        0.923
20638  1.8672  ...        0.847
20639  2.3886  ...        0.894

[20640 rows x 9 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB